Feature
basirking/My_Portfolio pull request #1
Opened 2022-04-21 09:05 UTC by basirking

2022-04-22 01:20 UTC, uche-inyama requested changes
### Hi @basirking :wave: 

Your project is coming alone just fine.

However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights


## Required Changes ♻️

- [ ] Add a [reset.css](https://meyerweb.com/eric/tools/css/reset/)  file to your project and include it inside your html header.
- [ ] Kindly use the font and colours defined in the figma template.
- [ ] Also, it would be nice if you format your html file, it is not properly indented.

#### Also Check the comments under the review.  :point_down: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-22 01:20 UTC, uche-inyama commented on style.css
> +}
If you intended for the two class names: connect and contact, to have access to these properties; kindy separate the property names with a comma. Also, note that there is no **contact** class in your html file.

2022-04-22 01:20 UTC, uche-inyama commented on index.html
> +
The logo should be inside a link tag:  ``<a>``

2022-04-22 01:20 UTC, uche-inyama commented on index.html
> +    </header>
Kindly add margin to header tag, to separate it from surrounding section. For example, margin button.

2022-04-22 01:20 UTC, uche-inyama commented on index.html
> +                </a>
Kindly use, ul and li tags to format your icons list.

2022-04-22 01:20 UTC, uche-inyama commented on index.html
> +      <a href="#">
Add margins to separate it from the upper section. For example: margin-top.

2022-04-22 16:13 UTC, uche-inyama requested changes
## Hi @basirking :slightly_smiling_face: 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has failed the linter check.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-04-22 17:25 UTC, xtrahuman requested changes
Hello @basirking, 

Good job so far!
you did a great job implementing most of the suggestions by the previous reviewer. There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- [x] GitHub flow
- [x] passed Linters  

## Required Changes ♻️
_Check the comments under the review._ ⬇️ ⬇️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-22 17:25 UTC, xtrahuman commented on style.css
> +.body-main {
Kindly reduce the margin-top to match the Figma design this class

Kindly increase the font size of your `h1` with the text content `i am basir nice to see you`
please ensure the rest of page properties such as font size, font family and margins matches with the Figma designs 

it will also be nice if your background images are in the exact position of the Figma design
I colored the areas you should try improving in the images below

This is the[ link](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122) to your figma design

![image](https://user-images.githubusercontent.com/43564324/164762646-c4a26799-b2bf-4bac-b0d3-00171c2b8ade.png)

2022-04-22 19:04 UTC, zieeco requested changes
Hi @basirking 

 <img src="https://media3.giphy.com/media/YT95XJOLvY1t2SJgpR/giphy.gif"/>

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-22 19:04 UTC, zieeco commented on style.css
> +  margin-top: 128px;
- [ ] Great on implementing the changes required by the previous reviewer, however, the marg-top is still too much and does not match the Figma design. Try fixing to match the design from [figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).

**YOUR DESIGN**  :point_down: 

![sorry](https://user-images.githubusercontent.com/59397159/164777313-2066d063-4923-4c6f-9060-602ce887563d.png)

2022-04-22 22:14 UTC, phelian23 requested changes
Hi @basirking, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-22 22:14 UTC, phelian23 commented on index.html
> +         <img class="logo" src="imgs/MyLogo.png" alt="logo">
- [ ] As requested by the first reviewer, kindly wrap the logo in an anchor `<a>` tag, it is good practice as it will serve as a direct one-click link to the homepage

2022-04-22 22:14 UTC, phelian23 commented on index.html
> +    top: 0px;"> -->
- [ ] [Optional] Kindly remove old pieces of code committed as inline comments. They will make your project look messy.  Remember if you need to review a previous version of your code, you can always use git history.

2022-04-23 11:35 UTC, Cathella approved these changes
## 🔥 Status: Approved 🟢

### Hi @basirking 👋🏻, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

![rosycheeks-mochi-peach](https://user-images.githubusercontent.com/4247740/164892760-b5ced82a-b6dc-40bc-931e-6a6e35190a45.gif)


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-23 11:38 UTC, merged