Desktop version
basirking/My_Portfolio pull request #5
Opened 2022-05-05 16:26 UTC by basirking

** in this version we:**
** -Add media queries to make the website responsive**
** -Add Desktop version portfolio**
** -Add new features to the file**

2022-05-05 18:09 UTC, zieeco requested changes
Hi @basirking 


Great work on your portfolio 👏 
You've done well implementing the design, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
- N/A 

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-05 18:09 UTC, zieeco commented on style.css
> +  }
- [ ] Please, kindly add the background image to your contact section.

2022-05-05 21:26 UTC, basirking commented on style.css
> +  }
what exactly should be the width??

2022-05-05 23:06 UTC, keroloussamy requested changes
Hi @basirking, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## To highlight 🎯

- No linter errors.✔️
- Good code design and implementation. ✔️

 ## Required Changes ♻️
_Check the comments under the review._

![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-05 23:06 UTC, keroloussamy commented on index.html
> +          </section>
- [ ] Kindly as asked by the previous reviewer, change the color for the section to white, and around it make it this degree of gray.
- [ ] Kindy as asked by the previous reviewer, make the button like the design the background white and the border blue.

Your design
![image](https://user-images.githubusercontent.com/35535130/167040024-25d9d814-cfcb-4265-9e11-9e30d87737b4.png)

Figma design
![image](https://user-images.githubusercontent.com/35535130/167040546-5a10618f-ccd1-4681-8b07-d7bf92b9a3c8.png)

2022-05-05 23:06 UTC, keroloussamy commented on index.html
>                 <li>
- [ ] Kindly as asked by the previous reviewer to follow the original design
- [ ] Kindly Make the button like the design the background white and the border blue.
- [ ] Kindly make the padding around the icons and the text equal to each other as the Figma design, and make the text on the left.

Your design
![image](https://user-images.githubusercontent.com/35535130/167040935-e2080d52-ce8f-4598-8a1e-1c3fb6cdb9a1.png)

Figma design
![image](https://user-images.githubusercontent.com/35535130/167040973-1cd12f43-fd04-4aa0-a206-af6f4ade9213.png)

2022-05-06 13:40 UTC, aimemalaika approved these changes
Hi @basirking, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![133591850-fdcb7dd3-dd7a-4274-81e7-0e59434148f7](https://user-images.githubusercontent.com/28307960/158747852-e9f4c957-d810-4de4-b468-69b1337714ea.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-06 13:53 UTC, merged